### ISSUE TITLE
fatal: unable to connect to github.com

### ISSUE THREAD

**Issue by yugandhar-btc** [GoogleCloudPlatform/solution-acceleration-toolkit#1148]
When i run the tfengine  facing with connecting, please help me on the same. 

$tfengine --config_path=$ENGINE_CONFIG --output_path=$GIT_ROOT/deployment/terraform

2022/07/12 12:28:52 template "mystudies": recipe "/xxxx/xxxx/xxx/xxxxx/xxxxxx/xxxxx.hcl": template "devops": error downloading '**git://github.com/GoogleCloudPlatform/healthcare-data-protection-suite?ref=templates-v0.7.0'**: /usr/bin/git exited with 128: Cloning into '/tmp/562709976/85195dca64baeaed05b44fe88acdf81b8e57bc5a4ef3e31c8723662c0f21e493'...
**fatal: unable to connect to github.com:**
github.com[0: 140.82.114.3]: errno=Connection timed out

**Comment by arolsmith** [comment]
Hello @yugandhar-btc 

I had the same issue because I hadn't used this solution for awhile, but then I had realized the recipe URL had changed in the docs. **git://github.com/** should actually be **github.com** when referencing the template remotely.

OLD format:
`git://github.com/GoogleCloudPlatform/healthcare-data-protection-suite//templates/tfengine/recipes/devops.hcl?ref=v0.7.0`

NEW format (the DevOps recipe, for example):
`github.com/GoogleCloudPlatform/healthcare-data-protection-suite//templates/tfengine/recipes/devops.hcl?ref=v0.7.0`

Hopefully this helps.

**Comment by yugandhar-btc** [comment]
@arolsmith this works... Thanks
